### ISSUE TITLE
ilab model train does not work without jsonl path in non-legacy mode

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1879] opened 2024-07-25 21:04 UTC
**Describe the bug**

**To Reproduce**
1. Run ilab model train without data path specified and without `--legacy`

**Expected behavior**
ilab model train works alone 

**Screenshots**

**Device Info (please complete the following information):**
 - Hardware Specs: [e.g. Apple M2 Pro Chip, 16 GB Memory, etc.]
 - OS Version: [e.g. Mac OS 14.4.1, Fedora Linux 40] Fedora Linux 40
 - Python Version: [output of `python --version`] 3.11
 - InstructLab Version: [output of `ilab --version`] 0.17

**Additional context**

**Comment by Max-Jesch** [comment] 2024-07-29 07:09
possible duplicate of https://github.com/instructlab/instructlab/issues/1820

**Comment by ktam3** [comment] 2024-08-05 18:45
Closing in favor of 1820

**Closed by ktam3** 2024-08-05 18:45 UTC
Labels: bug
