### ISSUE TITLE
EPIC: PyPI package prep

### ISSUE THREAD

**Issue by markstur** [instructlab/instructlab#256] opened 2024-03-04 16:36 UTC
Nothing is public yet, so we don't have a package on pypi.org (and shouldn't), but it would be good if someone handy w/ pypi publishing got us ready-to-go for this asap when approved.

**Comment by mairin** [comment] 2024-04-23 14:34
Ali talked to Christian about this last week - there's a way to do a test release. Let's aim to first do a test release on 5/2 milestone, and a full release by 5/30.

Charlie will make a child issue of this to track the 5/2 milestone test release.

**Comment by tiran** [comment] 2024-04-23 14:38
Test releases on test.pypi.org are easy, see PR #922 . I can make a PR to enable test releases now and see if the pipeline to Test PyPI works. It is going to push a new release after every PR merge.

**Comment by russellb** [comment] 2024-05-06 21:43
I believe this is almost "done" -- based on this workflow, the next time we do a release(0.15.0), we should get automatic publishing of the release to pypi.

https://github.com/instructlab/instructlab/blob/main/.github/workflows/pypi.yaml

**Comment by leseb** [comment] 2024-05-17 10:06
I see https://test.pypi.org/project/instructlab/ on test.pypi, now 0.15 is out but I don't see anything on https://pypi.org/. I see this publish was skip in this job https://github.com/instructlab/instructlab/actions/runs/9097562546 but I might be looking at the wrong one.

Thoughts?

**Comment by tiran** [comment] 2024-05-17 10:20
0.15.0 failed to deploy to test and prod PyPI. https://pypi.org/project/instructlab/ is there, but has no valid release. Let's see if 0.15.1 deploys correctly.

**Comment by nathan-weinberg** [comment] 2024-06-04 14:30
Can we close this now that PyPi packaging has been confirmed to be working?

**Comment by russellb** [comment] 2024-06-04 14:44
looks like we're good here!  Thanks!

**Closed as completed by russellb** 2024-06-04 14:44 UTC
Labels: enhancement
