### ISSUE TITLE
Github errors added to ilab generate

### ISSUE THREAD

**Issue by sodoherty-ai** [instructlab/instructlab#1026] opened 2024-04-29 06:01 UTC
Running a first time test the `ilab generate` won't work unless you have access to github. I created a blank repository on my own account. 

When your `ilab generate` runs it asks for a github username and password.  Github no longer supports this and throws an error. Generate still runs but mixes the github error into the training. 

Example: 

{
    "system": "You are an AI language model developed by IBM Research. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior.",
    "user": "What can I ask the GPT model about the error message?",
    "assistant": "You can ask the GPT model to explain the error in detail, provide suggestions for troubleshooting, or offer advice on how to prevent similar errors in the future."
}
{
    "system": "You are an AI language model developed by IBM Research. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior.",
    "user": "What can the GPT model tell me about the Git error message provided in the document?",
    "assistant": "The GPT model can provide insights into the Git error message, such as explaining the cause, suggesting solutions, or offering advice for preventing similar errors in the future."
}

The data I had was about conducting interviews with potential employees.

**Comment by booxter** [comment] 2024-04-29 17:24
@sodoherty-ai could you please share how you configure the environment? Have you run `ilab init`? Did it initialize `taxonomy` repository for you?

**Comment by sodoherty-ai** [comment] 2024-04-29 18:59
I followed the instructions on the readme.md. The taxonomy downloaded fine. But it pulls `.git` information. For some reason it asks for username/password to git when that information is there. 

This is the link it gives you about the user/pass. 

https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls

After deleting all the hidden git information it runs without asking for username/password.

**Comment by nathan-weinberg** [comment] 2024-07-30 19:26
@sodoherty-ai are you able to reproduce this issue with the latest `ilab` version?

**Comment by nathan-weinberg** [comment] 2024-08-19 19:42
Closing due to a lack of traction, feel free to reopen if this is still an issue

**Closed by nathan-weinberg** 2024-08-19 19:42 UTC
