### ISSUE TITLE
Extend InstructLab to support torch.device("hpu")

### ISSUE THREAD

**Issue by ktam3** [instructlab/instructlab#2219] opened 2024-09-09 12:13 UTC
InstructLab has to be extended to use torch.device("hpu") instead of device cuda / cpu. The device name should be a config option and CLI option. All occurrences of torch.cuda modules must be refactored to support other accelerator backends, too.

I recommend to make device support generic, so we can add new device types more easily. We may support Intel GPU or AI accelerators on IBM Z in the future.

See

https://github.com/instructlab/instructlab/blob/v0.18.4/src/instructlab/train/linux_train.py#L45-L66
https://github.com/instructlab/instructlab/pull/1015
Related to: https://github.com/instructlab/training/issues/197

**Comment by JamesKunstle** [comment] 2024-10-02 19:39
This is a duplicate of other issues covering working on Gaudi cards

**Closed by JamesKunstle** 2024-10-02 19:39 UTC
