### ISSUE TITLE
ilab taxonomy diff line length issue needs to be an error or warning

### ISSUE THREAD

**Issue by alinaryan** [instructlab/instructlab#1902] opened 2024-07-29 15:10 UTC
When running `ilab taxonomy diff' and there's an issue with the line length, it prints out as both a warning and fatal error. It should print out as one or the other, not both.

**Comment by bjhargrave** [comment] 2024-07-29 15:19
This is easy to do with the new taxonomy parsing api. But we also have a fidelity concern relative to the taxonomy repo. We want the taxonomy repo to have consistent yaml standards for contributions. We also want to make sure ilab taxonomy diff has the same or very similar standard to the taxonomy repo so users don't get a pass on the command line but get PR failures when the submit the yaml to the taxonomy repo. 

It is also possible for a user to alter the yaml config for the ilab taxonomy diff command to relax the line length standard.

**Comment by nathan-weinberg** [comment] 2024-07-29 17:40
@alinaryan i'm having issues reproducing this, do you have an example input?

**Comment by nathan-weinberg** [comment] 2024-07-29 20:03
Was able to reproduce by passing custom rules.

**Comment by nathan-weinberg** [comment] 2024-07-29 21:16
Discussed with @cdoern - the `warning` text is coming directly from `yamllint` but we are considering any `yamllint` errors to be blocking since invalid YAML cannot be used for SDG/Training. Given that we can't really modify the output from `yamllint` and `ilab` is returning what is expected, I'm going to close this.

**Closed by nathan-weinberg** 2024-07-29 21:16 UTC
Labels: bug
