### ISSUE TITLE
CI: `ilab model evaluate` in E2E runs are not incorporated into full ilab workflow

### ISSUE THREAD

**Issue by alimaredia** [instructlab/instructlab#1642] opened 2024-07-09 20:25 UTC
**Describe the bug**

The ilab workflow tested in basic-workflow-tests.sh (https://github.com/instructlab/instructlab/blob/main/scripts/basic-workflow-tests.sh#L196) tests model evaluation, however evaluation is not being tested as it would be run in the full ilab workflow.

As development for training and SDG happen, the following should be incorporated into the model evaluation happening in the CI

1. The models these commands are testing should be the new model trained by `ilab model train`.
2. The Base model for the `mt_bench_branch` and `mmlu_branch` should be the model before training.
3. The taxonomy used for `mt_bench_branch` should be the taxonomy that was changed before the SDG step.
4. The mmlu_pr questions used in mmlu_branch are generated from the SDG step (ilab data generate).

**Comment by nathan-weinberg** [comment] 2024-07-12 04:04
Happy to help y'all with this if you want

**Comment by nathan-weinberg** [comment] 2024-07-31 03:32
@alimaredia @alinaryan @russellb this seems to be a duplicate of https://github.com/instructlab/instructlab/issues/1540 - am I wrong? If not we should close one or the other

**Closed** 2024-09-27 20:03 UTC
Labels: CI/CD
