### ISSUE TITLE
Rename `sysinfo` to `info`

### ISSUE THREAD

**Issue by RobotSail** [instructlab/instructlab#1632] opened 2024-07-08 23:18 UTC
In PR #1471, we are moving the `sysinfo` command to be under the `system` command group, so now the usage is `system sysinfo`. 

Since this is very awkward to type out, we should rename it to `system info`.

**Comment by nathan-weinberg** [comment] 2024-07-12 20:50
Duplicate of https://github.com/instructlab/instructlab/issues/1661 which was resolved by https://github.com/instructlab/instructlab/pull/1662

**Closed by nathan-weinberg** 2024-07-12 20:50 UTC
Labels: enhancement
