### ISSUE TITLE
llama.cpp Python API server failed to load API definition

### ISSUE THREAD

**Issue by kingaj12** [instructlab/instructlab#1068] opened 2024-05-01 15:25 UTC
OS:  wsl2 Ubuntu 20.04
Python version: 3.11.4
Error: `Fetch error: Service unavailable /openapi.json`
Expected behavior: `http:127.0.0.1:8000/docs` displays swagger API definitions

Steps to reproduce:  

- install `ilab` per instructions on README.md
- browse to `http:127.0.0.1:8000/docs`

**Comment by tiran** [comment] 2024-05-02 07:28
The issue is caused by a certificate problem with cdn.jsdelivr.net, https://github.com/jsdelivr/jsdelivr/issues/18565

Workaround:
```shell
sed -i 's/cdn.jsdelivr.net/fastly.jsdelivr.net/g' YOUR/PATH/TO/fastapi/openapi/docs.py
```

**Comment by nathan-weinberg** [comment] 2024-05-03 18:24
Linked issue is resolved, @kingaj12 can you try to reproduce?

**Comment by tiran** [comment] 2024-05-03 18:30
Works for me without patching FastAPI.

**Comment by nathan-weinberg** [comment] 2024-05-03 18:41
I'm going to close this then - @kingaj12 if it's still an issue for you feel free to reopen

**Closed by nathan-weinberg** 2024-05-03 18:41 UTC
Labels: bug
