### ISSUE TITLE
Why is merlinite the default chat and generate model and granite the default train model?

### ISSUE THREAD

**Issue by maxdebayser** [instructlab/instructlab#2278] opened 2024-09-17 12:50 UTC
**What is the current experience of ilab you've found issue with?**

I've noticed that the default model used for training (granite) is different than the default model that is configured with `ilab config init` and downloaded with `ilab model download`. This forces the user to make yet another download of a model. This is inconvenient because:

1. It wastes disk space
2. Not everyone has fast internet
3. If you want to teach instructlab to a room full of people who then all use the same internet connection to download the model files things can get really slow.

It's also quite confusing because in the beginning you play with the merlinite model and you think "oh, it doesn't know X, let me add that knowledge". Then you train the granite model and now it knows the answer to your question but now you don't know if your training made the difference of if the granite base model already knew it.

**How do you think the described experience should be?**

The default model should be the same for all cases and ideally it should be quantized. If the default for chat is to download the quantized version and then for training you have to download the unquantized version, that would also be bad.

**What is the benefit of the change you are proposing?**

Less user confusion, less wasted bandwidth.

**Comment by nathan-weinberg** [comment] 2024-09-18 17:17
Duplicate of https://github.com/instructlab/instructlab/issues/2238 - feel free to chime in on that issue, but please look at existing issues before creating new ones, thanks

**Closed by nathan-weinberg** 2024-09-18 17:17 UTC
Labels: duplicate, UX
